#b!/usr/bin/perl
# Copyright 2014 Jeffrey Kegler
# This file is part of Libmarpa.  Libmarpa is free software: you can
# redistribute it and/or modify it under the terms of the GNU Lesser
# General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# Libmarpa is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser
# General Public License along with Libmarpa.  If not, see
# http://www.gnu.org/licenses/.

# Utility for rewriting Lua sources from their 'base' form
# into their 'rewritten' form.  The main object of the rewrite
# is to change the library prefix from 'lua' to 'marpa_lua'.
# The source is also rearrange into different files.

use 5.010;
use strict;
use warnings;
use autodie;
use English qw( -no_match_vars );
use File::Spec;

use Getopt::Long;
my $verbose = 1;
my $result = Getopt::Long::GetOptions( 'verbose=i' => \$verbose );
die "usage $PROGRAM_NAME [--verbose=n] file ...\n" if not $result;

sub slurp_and_rename {
    my ($file) = @_;
    local $RS = undef;
    open my $fh, q{<}, $file;
    my $contents = <$fh>;
    close $fh;
    $contents =~ s/lua_/marpa_lua_/gxms;
    $contents =~ s/lua (.) _/marpa_lua$1_/gxms;
    $contents =~ s/LUA_/MARPA_LUA_/gxms;
    return \$contents;
}

FILE: for my $base (<base/src/*.[ch]>, <base/src/*in>) {

    my ( $vol, undef, $file ) = File::Spec->splitpath($base);

    my $gen_dirs = File::Spec->catdir('gen');
    my $gen_file = File::Spec->catpath( $vol, $gen_dirs, $file );

    open my $fh, q{>}, $gen_file;
    say {$fh} <<'=== PREAMBLE ===';
/* This is an automatically generated file based on a Lua
  source file.  For licensing, set the approprate Lua source.
  This is not a source file. */

/* DO NOT EDIT THIS FILE */
=== PREAMBLE ===

    say {$fh} "This file was automatically generated by $PROGRAM_NAME at "
        . localtime();
    say {$fh} ${ slurp_and_rename('base/src/lapi.c') };
    close $fh;

} ## end for my $base (<base/src/*.[ch]>)
